# Yeah, we finally gonna see some basics!

### We will learn:

#### 1. The difference between strings and numbers.
#### 2. How use lists, arrays, and dictionaries.
#### 3. Basic math using numpy.
#### 4. Create a data frame using Pandas.

In [1]:
!python --version

Python 3.7.1


#### Let's start off with importing the packages we need. What should you do then?

In [2]:
# replace XXXXX with the name of the package and XX with the alias you want to use.
# import XXXXX as XX
# import XXXXX as XX

import numpy as np
import pandas as pd

### Strings
#### Strings are bits of text. They can be defined as anything between quotes

In [3]:
print("hello world!")

hello world!


#### Let's create a string and store it in a variable called mystring

In [4]:
mystring = "SauloIsTheBestTeacher"
print(type(mystring))
print(len(mystring))

<class 'str'>
21


### Basic Data Types in Python
#### int -> Integers
#### float -> Floating-Point Numbers.
#### complex -> Complex Numbers.
#### str -> Strings.
#### bool -> Boolean.

#### Slicing strings

In [5]:
print(mystring[0]) # first
print(mystring[-1]) # last
print(mystring[:5]) # first 5
print(mystring[-7:]) # last 6 (6+1)???

S
r
Saulo
Teacher


#### Manipulating

In [6]:
addstring = "Not"
newstring = mystring[:7] + addstring + mystring[7:] # concatenating
print(newstring)

SauloIsNotTheBestTeacher


In [7]:
print(len(newstring))
print(newstring.index('r'))

24
23


In [8]:
print(" ".join(newstring))
print("_".join(newstring))

S a u l o I s N o t T h e B e s t T e a c h e r
S_a_u_l_o_I_s_N_o_t_T_h_e_B_e_s_t_T_e_a_c_h_e_r


In [9]:
print(newstring.lower())
print(newstring.upper())

sauloisnotthebestteacher
SAULOISNOTTHEBESTTEACHER


In [10]:
checkvalue = newstring.startswith('S') # case sensitive
print(type(checkvalue))
print(checkvalue)

<class 'bool'>
True


#### Next we are going to learn what a list is and how to use loops in Python

In [13]:
wordslength = [5, 2, 3, 3, 4, 7] # this is a list

cc = 0
for i in wordslength: # here starts our loop
    print('word: ',newstring[cc:i+cc])
#     print('i, cc = ',i,',',cc)
    cc += i

word:  Saulo
word:  Is
word:  Not
word:  The
word:  Best
word:  Teacher


### - Lists are what they seem - a list of values. 
##### Each one of them is numbered, starting from zero - 
##### the first one is numbered zero, the second 1, the third 2, etc. You can remove values from the list, 
##### and add new values to the end. Example: Your many cats' names.

### - Tuples are just like lists, but you can't change their values.
##### The values that you give it first up, 
##### are the values that you are stuck with for the rest of the program. Again, each value is numbered starting from zero, 
##### for easy reference. Example: the names of the months of the year.

### - Dictionaries are similar to what their name suggests - a dictionary. 
##### In a dictionary, you have an 'index' of words, and for each of them a definition. 
##### In python, the word is called a 'key', and the definition a 'value'.
##### The values in a dictionary aren't numbered - tare similar to what their name suggests - a dictionary. 
##### In a dictionary, you have an 'index' of words, and for each of them a definition. 
##### In python, the word is called a 'key', and the definition a 'value'. 
##### The values in a dictionary aren't numbered - they aren't in any specific order, either - the key does the same thing. 
##### You can add, remove, and modify the values in dictionaries. Example: telephone book.

### - An array is a data structure that stores values of same data type. 
##### In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to 
##### different data types, arrays in python can only contain values corresponding to same data type.

### Numbers
#### Number data types store numeric values.
#### int (signed integers) − They are often called just integers or ints, are positive or negative whole numbers with no decimal point.
#### float (floating point real values) − Also called floats, they represent real numbers and are written with a decimal point dividing the integer and fractional parts. Floats may also be in scientific notation, with E or e indicating the power of 10 (2.5e2 = 2.5 x 102 = 250).

In [14]:
n1 = 100
n2 = 100. # note the point here
print(type(n1),type(n2))

<class 'int'> <class 'float'>


In [15]:
print('100'+'100')
print(100+100)
print(100.+100.)

100100
200
200.0


In [16]:
my2Darray = np.array( [ [1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15] ] )
print(my2Darray)
print(type(my2Darray))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>


#### Basic operations

In [17]:
print(my2Darray.sum(axis=0)) # axis 0 - rows
print(my2Darray.sum(axis=1)) # axis 1 - columns
print(my2Darray.sum(axis=(0,1))) 

[18 21 24 27 30]
[15 40 65]
120


In [18]:
print(my2Darray.shape) # nrows vs ncol
print(my2Darray.T.shape) # transpose 
print(my2Darray.size) # total number of elements

(3, 5)
(5, 3)
15


In [19]:
my1Darray = np.array( [ [-1, -2, -3, -4, -5] ] )

print(my1Darray.shape) # nrows vs ncol
print(my1Darray.T.shape) # transpose 

(1, 5)
(5, 1)


In [20]:
print(my2Darray + my1Darray) 

[[ 0  0  0  0  0]
 [ 5  5  5  5  5]
 [10 10 10 10 10]]


In [21]:
print(my2Darray.dot(my1Darray.T)) # matrix multiplication (dot product)

[[ -55]
 [-130]
 [-205]]


#### Slicing

In [22]:
print(my2Darray)
print(my2Darray[0,0])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
1


In [23]:
print(my2Darray[:,0]) # all rows from first column
print(my2Darray[0,:]) # all columns from first row

[ 1  6 11]
[1 2 3 4 5]


In [24]:
print('row: first 2 rows; column: last four columns ', my2Darray[:2,1:] )

row: first 2 rows; column: last four columns  [[ 2  3  4  5]
 [ 7  8  9 10]]


In [25]:
print(my2Darray > 3)

[[False False False  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [26]:
print(my1Darray*2) # multiply by 2
print(my1Darray**2) # to the power 2

[[ -2  -4  -6  -8 -10]]
[[ 1  4  9 16 25]]


#### Let's now create a dictionary

In [27]:
mydict = dict( name=mystring, number=my2Darray )
# alternatively
# mydict = {'name':mystring,'number':my2Darray}
print(mydict)

{'name': 'SauloIsTheBestTeacher', 'number': array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])}


#### A dictionary maps a set of objects (keys) to another set of objects (values). A Python dictionary is a mapping of unique keys to values. 

In [28]:
print(mydict.keys())

dict_keys(['name', 'number'])


In [29]:
mylongdict = dict(name=['Saulo', 'Linda', 'Shabnam'], age=[52, 18, 22], salary=[10.**2,10.**6,10.**6*2])
print(mylongdict)

{'name': ['Saulo', 'Linda', 'Shabnam'], 'age': [52, 18, 22], 'salary': [100.0, 1000000.0, 2000000.0]}


In [30]:
df = pd.DataFrame.from_dict(mylongdict)

In [31]:
df

name  age     salary
0    Saulo   52      100.0
1    Linda   18  1000000.0
2  Shabnam   22  2000000.0

In [32]:
df.plot.bar(x='name',y='salary')

List of references:

##### https://www.learnpython.org/en/Basic_String_Operations
##### https://www.tutorialspoint.com/python/python_numbers.htm
##### http://sthurlow.com/python/lesson06/
##### http://cs231n.github.io/python-numpy-tutorial/#numpy-arrays
##### https://www.pythonforbeginners.com/dictionary/how-to-use-dictionaries-in-python/